### ISSUE TITLE
Support for going through IAM VPE endpoint

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-iam-account-settings#157]
Check that the logic at https://github.com/terraform-ibm-modules/terraform-ibm-iam-account-settings/blob/afe0609e15e58e5aed854633e5a8a6e4a993942a/main.tf#L39 can work through the IAM VPE endpoint. In therory, it should, but this requires validation.

**Comment by vburckhardt** [comment]
Also expose the local as a variable at https://github.com/terraform-ibm-modules/terraform-ibm-iam-account-settings/blob/f65b35bd55431a0d72e2a8a22b1a31dff3708d59/main.tf#L55

**Comment by ocofaigh** [comment]
We already have an internal issue to migrate to ibm provider. Will get it worked on as a priority. This should remove the need to have to provider endpoint types here

**Comment by ocofaigh** [comment]
restapi provider has been removed in https://github.com/terraform-ibm-modules/terraform-ibm-iam-account-settings/pull/214 and replaced by IBM provider. Closing this
